apiVersion: v1
kind: Pod
metadata:
   name: thelounge
   labels:
     app: irc
spec:
   containers:
     - name: thelounge
       image: linuxserver/thelounge
       ports:
         - containerPort: 9000
           name: "irc-http"


