apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdimage
  labels:
    app: cicdimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicdimage
  template:
    metadata:
      labels:
        app: cicdimage
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cicdimage
        image: jagdishmohite/cicdimage
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
