apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-image
  labels:
    app: cicd-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-image
  template:
    metadata:
      labels:
        app: cicd-image
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cicd-image
        image: jagdishmohite/cicdimage
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
