apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdapp
  labels:
    app: cicdapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicdappp
  template:
    metadata:
      labels:
        app: cicdapp
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cicdapp
        image: jagdishmohite/cicdimage:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
