kind: Service                             
apiVersion: v1
metadata:
  name: thelounge
  labels:
    app: thelounge
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: thelounge                   
  type: LoadBalancer
